/*
  Warnings:

  - The values [EMAIL_UPDATE_FAILED] on the enum `AuditAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('USER_REGISTER', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOGOUT_ALL_DEVICES', 'USER_LOGOUT_OTHER_DEVICES', 'EMAIL_VERIFIED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'TOKEN_REFRESHED', 'ROLE_CHANGED', 'USER_DELETED', 'USERS_BULK_DELETED', 'SESSION_REVOKED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'LOGIN_FAILED', 'VERIFICATION_EMAIL_SENT', 'RESET_EMAIL_SENT', 'USER_DATA_EXPORTED', 'USER_DATA_ANONYMIZED', 'USER_PERMANENTLY_DELETED', 'EMAIL_UPDATED', 'MAGIC_LINK_REQUESTED', 'MAGIC_LINK_SENT', 'MAGIC_LINK_LOGIN', 'MAGIC_LINK_FAILED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;
